name: "Post to Bluesky"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6,18 * * *"
  push:
    branches:
      - main

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'
      - run: npm ci
      - name: Send post
        env:
          BLUESKY_BOT_USERNAME: ${{ secrets.BLUESKY_BOT_USERNAME }}
          BLUESKY_BOT_PASSWORD: ${{ secrets.BLUESKY_BOT_PASSWORD }}
          ##NODE_OPTIONS: "--dns-result-order=ipv4first"
        run:
          node bot.js